/*
* generated by Xtext
*/
package com.polopoly.ps.dsl.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import com.polopoly.ps.dsl.services.TextContentGrammarAccess;

public class TextContentParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TextContentGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected com.polopoly.ps.dsl.parser.antlr.internal.InternalTextContentParser createParser(XtextTokenStream stream) {
		return new com.polopoly.ps.dsl.parser.antlr.internal.InternalTextContentParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "TextContent";
	}
	
	public TextContentGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TextContentGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
