/*
* generated by Xtext
*/
package com.polopoly.ps.dsl.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class TextContentAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("com/polopoly/ps/dsl/parser/antlr/internal/InternalTextContent.tokens");
	}
}
