/*
 * generated by Xtext
 */
package com.polopoly.ps.dsl.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class TextContentUiModule extends com.polopoly.ps.dsl.ui.AbstractTextContentUiModule {
	public TextContentUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
