/*
 * generated by Xtext
 */
package com.polopoly.ps.dsl.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class TextContentExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return com.polopoly.ps.dsl.ui.internal.TextContentActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return com.polopoly.ps.dsl.ui.internal.TextContentActivator.getInstance().getInjector("com.polopoly.ps.dsl.TextContent");
	}
	
}
