/*
 * generated by Xtext
 */
package com.polopoly.ps.dsl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class TextContentRuntimeModule extends com.polopoly.ps.dsl.AbstractTextContentRuntimeModule {

}
