/*
* generated by Xtext
*/
package com.polopoly.ps.dsl.ui.contentassist;

import com.polopoly.ps.dsl.ui.contentassist.AbstractTextContentProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class TextContentProposalProvider extends AbstractTextContentProposalProvider {

}
