/*
* generated by Xtext
*/
package com.polopoly.ps.dsl;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class TextContentUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return com.polopoly.ps.dsl.ui.internal.TextContentActivator.getInstance().getInjector("com.polopoly.ps.dsl.TextContent");
	}
	
}
